icon: 🐃
limits:
  maxWeight: 700
  maxAmount: 10
  maxSpeed: 3
  maxFood: 100
stringTargetMatrix:
  Wolf: 0
  Boa: 0
  Fox: 0
  Bear: 0
  Eagle: 0
  Horse: 0
  Deer: 0
  Rabbit: 0
  Mouse: 0
  Goat: 0
  Sheep: 0
  Boar: 0
  Duck: 0
  Caterpillar: 0
  Cactus: 100
  Tree: 30
  Bush: 70
  Grass: 100
