icon: 🦅
limits:
  maxWeight: 6
  maxAmount: 20
  maxSpeed: 3
  maxFood: 1
stringTargetMatrix:
  Wolf: 0
  Boa: 0
  Fox: 10
  Bear: 0
  Horse: 0
  Deer: 0
  Rabbit: 90
  Mouse: 90
  Goat: 0
  Sheep: 0
  Boar: 0
  Buffalo: 0
  Duck: 80
  Caterpillar: 0
  Grass: 0
